version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Add monitoring with health checks
  health:
    image: alpine:latest
    command: |
      sh -c "
        while true; do
          if wget --quiet --tries=1 --spider http://app:80; then
            echo 'App is healthy'
          else
            echo 'App is unhealthy'
          fi
          sleep 30
        done
      "
    depends_on:
      - app
    restart: unless-stopped